//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoSOS.ArcMapAddIn.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_en() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeoSOS.ArcMapAddIn.Properties.Resource_en", typeof(Resource_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Configuration Wizard of ANN-CA 的本地化字符串。
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select proper land use character for all land use types 的本地化字符串。
        /// </summary>
        internal static string String10 {
            get {
                return ResourceManager.GetString("String10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All configurations for Logistic-CA are listed below:  的本地化字符串。
        /// </summary>
        internal static string String100 {
            get {
                return ResourceManager.GetString("String100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  simulation, Start Time:  的本地化字符串。
        /// </summary>
        internal static string String101 {
            get {
                return ResourceManager.GetString("String101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ANN-CA 的本地化字符串。
        /// </summary>
        internal static string String102 {
            get {
                return ResourceManager.GetString("String102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DecisionTree-CA 的本地化字符串。
        /// </summary>
        internal static string String103 {
            get {
                return ResourceManager.GetString("String103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logistic-CA 的本地化字符串。
        /// </summary>
        internal static string String104 {
            get {
                return ResourceManager.GetString("String104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Accuracy 的本地化字符串。
        /// </summary>
        internal static string String105 {
            get {
                return ResourceManager.GetString("String105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    This wizard will guide you to finish the configurations for ANN-CA simulations. 的本地化字符串。
        /// </summary>
        internal static string String106 {
            get {
                return ResourceManager.GetString("String106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Induction of ANN-CA 的本地化字符串。
        /// </summary>
        internal static string String107 {
            get {
                return ResourceManager.GetString("String107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    Induction of the theory on artifical neural network based CA. 的本地化字符串。
        /// </summary>
        internal static string String108 {
            get {
                return ResourceManager.GetString("String108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spatial Variables Layer Name 的本地化字符串。
        /// </summary>
        internal static string String109 {
            get {
                return ResourceManager.GetString("String109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sampling..... 的本地化字符串。
        /// </summary>
        internal static string String11 {
            get {
                return ResourceManager.GetString("String11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value 的本地化字符串。
        /// </summary>
        internal static string String110 {
            get {
                return ResourceManager.GetString("String110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        internal static string String111 {
            get {
                return ResourceManager.GetString("String111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is Urban 的本地化字符串。
        /// </summary>
        internal static string String112 {
            get {
                return ResourceManager.GetString("String112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color 的本地化字符串。
        /// </summary>
        internal static string String113 {
            get {
                return ResourceManager.GetString("String113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Training Data Configuration 的本地化字符串。
        /// </summary>
        internal static string String114 {
            get {
                return ResourceManager.GetString("String114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   Set the land use data, spatial variables and other configurations for ANN training. 的本地化字符串。
        /// </summary>
        internal static string String115 {
            get {
                return ResourceManager.GetString("String115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Training Data Sampling 的本地化字符串。
        /// </summary>
        internal static string String116 {
            get {
                return ResourceManager.GetString("String116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   Sample the data for training, and set the land use types info. 的本地化字符串。
        /// </summary>
        internal static string String117 {
            get {
                return ResourceManager.GetString("String117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Artificial Neural Network Training 的本地化字符串。
        /// </summary>
        internal static string String118 {
            get {
                return ResourceManager.GetString("String118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   Train the ANN for calculating conversion probabilities of all land use types by input data. 的本地化字符串。
        /// </summary>
        internal static string String119 {
            get {
                return ResourceManager.GetString("String119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reading initial land use data  的本地化字符串。
        /// </summary>
        internal static string String12 {
            get {
                return ResourceManager.GetString("String12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Simulation/Prediction Data Configuration 的本地化字符串。
        /// </summary>
        internal static string String120 {
            get {
                return ResourceManager.GetString("String120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   Set land use data, number of cells need to be converted, iterations for a simulation/prediction. 的本地化字符串。
        /// </summary>
        internal static string String121 {
            get {
                return ResourceManager.GetString("String121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Simulation/Prediction Parameters Configuration 的本地化字符串。
        /// </summary>
        internal static string String122 {
            get {
                return ResourceManager.GetString("String122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   Set all parameters for a simulation/prediction. 的本地化字符串。
        /// </summary>
        internal static string String123 {
            get {
                return ResourceManager.GetString("String123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Simulation/Prediction Process Configuration 的本地化字符串。
        /// </summary>
        internal static string String124 {
            get {
                return ResourceManager.GetString("String124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   Set the refresh and output configurations for a simulation/prediction. 的本地化字符串。
        /// </summary>
        internal static string String125 {
            get {
                return ResourceManager.GetString("String125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configuration Finished 的本地化字符串。
        /// </summary>
        internal static string String126 {
            get {
                return ResourceManager.GetString("String126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   Check the summary below. Click “Finish” to start the simulation/prediction. 的本地化字符串。
        /// </summary>
        internal static string String127 {
            get {
                return ResourceManager.GetString("String127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Land use character 的本地化字符串。
        /// </summary>
        internal static string String128 {
            get {
                return ResourceManager.GetString("String128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Variables Name 的本地化字符串。
        /// </summary>
        internal static string String129 {
            get {
                return ResourceManager.GetString("String129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reading ending land use data  的本地化字符串。
        /// </summary>
        internal static string String13 {
            get {
                return ResourceManager.GetString("String13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Coefficients 的本地化字符串。
        /// </summary>
        internal static string String130 {
            get {
                return ResourceManager.GetString("String130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Standard Errors 的本地化字符串。
        /// </summary>
        internal static string String131 {
            get {
                return ResourceManager.GetString("String131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 95% Confidence Intervals Upper Bound 的本地化字符串。
        /// </summary>
        internal static string String132 {
            get {
                return ResourceManager.GetString("String132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 95% Confidence Intervals Lower Bound 的本地化字符串。
        /// </summary>
        internal static string String133 {
            get {
                return ResourceManager.GetString("String133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configuration Wizard of Logistic-CA 的本地化字符串。
        /// </summary>
        internal static string String134 {
            get {
                return ResourceManager.GetString("String134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    This wizard will guide you to finish the configurations for Logistic-CA simulations. 的本地化字符串。
        /// </summary>
        internal static string String135 {
            get {
                return ResourceManager.GetString("String135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Induction of Logistic-CA 的本地化字符串。
        /// </summary>
        internal static string String136 {
            get {
                return ResourceManager.GetString("String136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    Induction of the theory on logistic regression based CA. 的本地化字符串。
        /// </summary>
        internal static string String137 {
            get {
                return ResourceManager.GetString("String137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    Set the land use data, spatial variables and other configurations for logistic regression. 的本地化字符串。
        /// </summary>
        internal static string String138 {
            get {
                return ResourceManager.GetString("String138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Land Use Type Configuration 的本地化字符串。
        /// </summary>
        internal static string String139 {
            get {
                return ResourceManager.GetString("String139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reading spatial variables:  的本地化字符串。
        /// </summary>
        internal static string String14 {
            get {
                return ResourceManager.GetString("String14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    Set value, description, character and color for all land use types. 的本地化字符串。
        /// </summary>
        internal static string String140 {
            get {
                return ResourceManager.GetString("String140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logistic Regression Calclulation 的本地化字符串。
        /// </summary>
        internal static string String141 {
            get {
                return ResourceManager.GetString("String141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    Calculate regression coefficients for all variables. 的本地化字符串。
        /// </summary>
        internal static string String142 {
            get {
                return ResourceManager.GetString("String142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configuration Wizard of DecisionTree-CA 的本地化字符串。
        /// </summary>
        internal static string String143 {
            get {
                return ResourceManager.GetString("String143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    This wizard will guide you to finish the configurations for DecisionTree-CA simulations. 的本地化字符串。
        /// </summary>
        internal static string String144 {
            get {
                return ResourceManager.GetString("String144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Induction of DecisionTree-CA 的本地化字符串。
        /// </summary>
        internal static string String145 {
            get {
                return ResourceManager.GetString("String145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    Induction of the theory on decision tree based CA. 的本地化字符串。
        /// </summary>
        internal static string String146 {
            get {
                return ResourceManager.GetString("String146", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    Set the land use data, spatial variables and other configurations for generating decision tree. 的本地化字符串。
        /// </summary>
        internal static string String147 {
            get {
                return ResourceManager.GetString("String147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generating Decision Tree 的本地化字符串。
        /// </summary>
        internal static string String148 {
            get {
                return ResourceManager.GetString("String148", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   Generate decision tree to obtain all transition rules. 的本地化字符串。
        /// </summary>
        internal static string String149 {
            get {
                return ResourceManager.GetString("String149", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Intercept 的本地化字符串。
        /// </summary>
        internal static string String15 {
            get {
                return ResourceManager.GetString("String15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sum of all cells 的本地化字符串。
        /// </summary>
        internal static string String150 {
            get {
                return ResourceManager.GetString("String150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Land Development Intensity (%) 的本地化字符串。
        /// </summary>
        internal static string String151 {
            get {
                return ResourceManager.GetString("String151", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Urban Growth Rate (%) 的本地化字符串。
        /// </summary>
        internal static string String152 {
            get {
                return ResourceManager.GetString("String152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select land use data to analyze. 的本地化字符串。
        /// </summary>
        internal static string String153 {
            get {
                return ResourceManager.GetString("String153", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save to Excel file 的本地化字符串。
        /// </summary>
        internal static string String154 {
            get {
                return ResourceManager.GetString("String154", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Excel file has been saved. 的本地化字符串。
        /// </summary>
        internal static string String155 {
            get {
                return ResourceManager.GetString("String155", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 说明：进行同一区域两个时段土地利用分类数据对比，可得到混淆矩阵及Kappa值。 的本地化字符串。
        /// </summary>
        internal static string String156 {
            get {
                return ResourceManager.GetString("String156", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起始时期土地利用分类数据： 的本地化字符串。
        /// </summary>
        internal static string String157 {
            get {
                return ResourceManager.GetString("String157", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 终止时期土地利用分类数据： 的本地化字符串。
        /// </summary>
        internal static string String158 {
            get {
                return ResourceManager.GetString("String158", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模拟结果数据： 的本地化字符串。
        /// </summary>
        internal static string String159 {
            get {
                return ResourceManager.GetString("String159", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select initail land use data for simulation/prediction. 的本地化字符串。
        /// </summary>
        internal static string String16 {
            get {
                return ResourceManager.GetString("String16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 说明：进行模拟结果与真实土地利用分类数据对比，可得到混淆矩阵、Kappa值和各类精度值。 的本地化字符串。
        /// </summary>
        internal static string String160 {
            get {
                return ResourceManager.GetString("String160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模拟终止时刻真实土地利用分类数据： 的本地化字符串。
        /// </summary>
        internal static string String161 {
            get {
                return ResourceManager.GetString("String161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 说明：进行模拟起始时刻、终止时刻真实土地利用分类数据与模拟结果对比，可得到基于FoM的各类结果值。 的本地化字符串。
        /// </summary>
        internal static string String162 {
            get {
                return ResourceManager.GetString("String162", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please open the tutorial Mxd File - &quot;LandUseChange_DongGuan.mxd”, located in: software decompression folder &amp; “\Tutorial Data\TutorialData_DongGuan_80m”. 的本地化字符串。
        /// </summary>
        internal static string String17 {
            get {
                return ResourceManager.GetString("String17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All configurations for DecisionTree-CA are listed below:  的本地化字符串。
        /// </summary>
        internal static string String18 {
            get {
                return ResourceManager.GetString("String18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Regression coefficients of all spatial variables are:  的本地化字符串。
        /// </summary>
        internal static string String19 {
            get {
                return ResourceManager.GetString("String19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prompt 的本地化字符串。
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Constant 的本地化字符串。
        /// </summary>
        internal static string String20 {
            get {
                return ResourceManager.GetString("String20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   Coefficient:  的本地化字符串。
        /// </summary>
        internal static string String21 {
            get {
                return ResourceManager.GetString("String21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Number of cells that are expected to convert:  的本地化字符串。
        /// </summary>
        internal static string String22 {
            get {
                return ResourceManager.GetString("String22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   cells. 的本地化字符串。
        /// </summary>
        internal static string String23 {
            get {
                return ResourceManager.GetString("String23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   iterations. 的本地化字符串。
        /// </summary>
        internal static string String24 {
            get {
                return ResourceManager.GetString("String24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Converted cells in one iteration:  的本地化字符串。
        /// </summary>
        internal static string String25 {
            get {
                return ResourceManager.GetString("String25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stochastic Disturbance Coefficient :  的本地化字符串。
        /// </summary>
        internal static string String26 {
            get {
                return ResourceManager.GetString("String26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Land use type name and value of urban:  的本地化字符串。
        /// </summary>
        internal static string String27 {
            get {
                return ResourceManager.GetString("String27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   Value:  的本地化字符串。
        /// </summary>
        internal static string String28 {
            get {
                return ResourceManager.GetString("String28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Land use type values that can be converted to urban:  的本地化字符串。
        /// </summary>
        internal static string String29 {
            get {
                return ResourceManager.GetString("String29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confusion Matrix of Simulated Data and Validation Data:  的本地化字符串。
        /// </summary>
        internal static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Land use type values that can&apos;t be converted to urban:  的本地化字符串。
        /// </summary>
        internal static string String30 {
            get {
                return ResourceManager.GetString("String30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Number of iterations:  的本地化字符串。
        /// </summary>
        internal static string String31 {
            get {
                return ResourceManager.GetString("String31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configurations of refresh and output:  的本地化字符串。
        /// </summary>
        internal static string String32 {
            get {
                return ResourceManager.GetString("String32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Every  的本地化字符串。
        /// </summary>
        internal static string String33 {
            get {
                return ResourceManager.GetString("String33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   iterations map, output info and graph will be refreshed. 的本地化字符串。
        /// </summary>
        internal static string String34 {
            get {
                return ResourceManager.GetString("String34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   iterations the intermediate data will be outputted. 的本地化字符串。
        /// </summary>
        internal static string String35 {
            get {
                return ResourceManager.GetString("String35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output folder path:  的本地化字符串。
        /// </summary>
        internal static string String36 {
            get {
                return ResourceManager.GetString("String36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creating simulated land use data  的本地化字符串。
        /// </summary>
        internal static string String37 {
            get {
                return ResourceManager.GetString("String37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configuration for CA simulation is finished. Please click “Start” button in GeoSOS toolbar to start the simulation process. 的本地化字符串。
        /// </summary>
        internal static string String38 {
            get {
                return ResourceManager.GetString("String38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A simulation process is running, please stop it then restart a new simulation process. 的本地化字符串。
        /// </summary>
        internal static string String39 {
            get {
                return ResourceManager.GetString("String39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select a land use data of end time for mining the land use transition rules. 的本地化字符串。
        /// </summary>
        internal static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Land Use Amount 的本地化字符串。
        /// </summary>
        internal static string String40 {
            get {
                return ResourceManager.GetString("String40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Intertions 的本地化字符串。
        /// </summary>
        internal static string String41 {
            get {
                return ResourceManager.GetString("String41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Amount 的本地化字符串。
        /// </summary>
        internal static string String42 {
            get {
                return ResourceManager.GetString("String42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Simulation Process:  的本地化字符串。
        /// </summary>
        internal static string String43 {
            get {
                return ResourceManager.GetString("String43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Null Value 的本地化字符串。
        /// </summary>
        internal static string String44 {
            get {
                return ResourceManager.GetString("String44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Iteration:  的本地化字符串。
        /// </summary>
        internal static string String45 {
            get {
                return ResourceManager.GetString("String45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   的本地化字符串。
        /// </summary>
        internal static string String46 {
            get {
                return ResourceManager.GetString("String46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Amount of Urban Cells:  的本地化字符串。
        /// </summary>
        internal static string String47 {
            get {
                return ResourceManager.GetString("String47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finish Simulation Process. 的本地化字符串。
        /// </summary>
        internal static string String48 {
            get {
                return ResourceManager.GetString("String48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time Elasped of Current Simulation:  的本地化字符串。
        /// </summary>
        internal static string String49 {
            get {
                return ResourceManager.GetString("String49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select spatial variables. 的本地化字符串。
        /// </summary>
        internal static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   seconds. 的本地化字符串。
        /// </summary>
        internal static string String50 {
            get {
                return ResourceManager.GetString("String50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Conversion result 的本地化字符串。
        /// </summary>
        internal static string String51 {
            get {
                return ResourceManager.GetString("String51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XML file(*.xml)|*.xml 的本地化字符串。
        /// </summary>
        internal static string String52 {
            get {
                return ResourceManager.GetString("String52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open land use type config file 的本地化字符串。
        /// </summary>
        internal static string String53 {
            get {
                return ResourceManager.GetString("String53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save land use type config file 的本地化字符串。
        /// </summary>
        internal static string String54 {
            get {
                return ResourceManager.GetString("String54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Config file is saved. 的本地化字符串。
        /// </summary>
        internal static string String55 {
            get {
                return ResourceManager.GetString("String55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CA Simulation - Logistic Regression Algorithm 的本地化字符串。
        /// </summary>
        internal static string String56 {
            get {
                return ResourceManager.GetString("String56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   的本地化字符串。
        /// </summary>
        internal static string String57 {
            get {
                return ResourceManager.GetString("String57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reading Simulation Data:  的本地化字符串。
        /// </summary>
        internal static string String58 {
            get {
                return ResourceManager.GetString("String58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Simulation Process is Paused 的本地化字符串。
        /// </summary>
        internal static string String59 {
            get {
                return ResourceManager.GetString("String59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can be converted to urban 的本地化字符串。
        /// </summary>
        internal static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Simulation Process is Proceeding 的本地化字符串。
        /// </summary>
        internal static string String60 {
            get {
                return ResourceManager.GetString("String60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Simulation Process is Stopped 的本地化字符串。
        /// </summary>
        internal static string String61 {
            get {
                return ResourceManager.GetString("String61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please open “GeoSOS for ArcGIS User Manual.pdf” in “User Manual” folder under the software decompression folder. Or get help at http://www.geosimulation.cn/usermanual_arcgisaddin.html . 的本地化字符串。
        /// </summary>
        internal static string String62 {
            get {
                return ResourceManager.GetString("String62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generating tree, it&apos;ll take a while, please be patient….. 的本地化字符串。
        /// </summary>
        internal static string String63 {
            get {
                return ResourceManager.GetString("String63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Number of sampled records is  的本地化字符串。
        /// </summary>
        internal static string String64 {
            get {
                return ResourceManager.GetString("String64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   . 的本地化字符串。
        /// </summary>
        internal static string String65 {
            get {
                return ResourceManager.GetString("String65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please chose at least one land use type as urban land use. 的本地化字符串。
        /// </summary>
        internal static string String66 {
            get {
                return ResourceManager.GetString("String66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ANN training is not finished. Please click “Start” button to begin the training procedure. 的本地化字符串。
        /// </summary>
        internal static string String67 {
            get {
                return ResourceManager.GetString("String67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sampling Completed! 的本地化字符串。
        /// </summary>
        internal static string String68 {
            get {
                return ResourceManager.GetString("String68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Training Completed 的本地化字符串。
        /// </summary>
        internal static string String69 {
            get {
                return ResourceManager.GetString("String69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cann&apos;t be converted to urban 的本地化字符串。
        /// </summary>
        internal static string String7 {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open conversion suitability configuration file 的本地化字符串。
        /// </summary>
        internal static string String70 {
            get {
                return ResourceManager.GetString("String70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save conversion suitability configuration file 的本地化字符串。
        /// </summary>
        internal static string String71 {
            get {
                return ResourceManager.GetString("String71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All configurations for ANN-CA are listed below:  的本地化字符串。
        /// </summary>
        internal static string String72 {
            get {
                return ResourceManager.GetString("String72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spatial variables layers are:  的本地化字符串。
        /// </summary>
        internal static string String73 {
            get {
                return ResourceManager.GetString("String73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All land use names and values are:  的本地化字符串。
        /// </summary>
        internal static string String74 {
            get {
                return ResourceManager.GetString("String74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Neighbor window size:  的本地化字符串。
        /// </summary>
        internal static string String75 {
            get {
                return ResourceManager.GetString("String75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Land use data of initial time:  的本地化字符串。
        /// </summary>
        internal static string String76 {
            get {
                return ResourceManager.GetString("String76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Land use data for validation:  的本地化字符串。
        /// </summary>
        internal static string String77 {
            get {
                return ResourceManager.GetString("String77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Conversion threshold:  的本地化字符串。
        /// </summary>
        internal static string String78 {
            get {
                return ResourceManager.GetString("String78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Land use conversion suitability matrix:  的本地化字符串。
        /// </summary>
        internal static string String79 {
            get {
                return ResourceManager.GetString("String79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Urban 的本地化字符串。
        /// </summary>
        internal static string String8 {
            get {
                return ResourceManager.GetString("String8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CA Simulation - Artificial Neural Network Algorithm 的本地化字符串。
        /// </summary>
        internal static string String80 {
            get {
                return ResourceManager.GetString("String80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CA Simulation - Decision Tree Algorithm 的本地化字符串。
        /// </summary>
        internal static string String81 {
            get {
                return ResourceManager.GetString("String81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start  的本地化字符串。
        /// </summary>
        internal static string String82 {
            get {
                return ResourceManager.GetString("String82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Accuracy of Current Simulation： 的本地化字符串。
        /// </summary>
        internal static string String83 {
            get {
                return ResourceManager.GetString("String83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confusion Matrix of Simulated Data and Validation Data： 的本地化字符串。
        /// </summary>
        internal static string String84 {
            get {
                return ResourceManager.GetString("String84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Overall Accuracy： 的本地化字符串。
        /// </summary>
        internal static string String85 {
            get {
                return ResourceManager.GetString("String85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kappa Value： 的本地化字符串。
        /// </summary>
        internal static string String86 {
            get {
                return ResourceManager.GetString("String86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FoM Value： 的本地化字符串。
        /// </summary>
        internal static string String87 {
            get {
                return ResourceManager.GetString("String87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Producer Accuracy： 的本地化字符串。
        /// </summary>
        internal static string String88 {
            get {
                return ResourceManager.GetString("String88", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Accuracy： 的本地化字符串。
        /// </summary>
        internal static string String89 {
            get {
                return ResourceManager.GetString("String89", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Calculating ... 的本地化字符串。
        /// </summary>
        internal static string String9 {
            get {
                return ResourceManager.GetString("String9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Overall 的本地化字符串。
        /// </summary>
        internal static string String90 {
            get {
                return ResourceManager.GetString("String90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Number 的本地化字符串。
        /// </summary>
        internal static string String91 {
            get {
                return ResourceManager.GetString("String91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Percent 的本地化字符串。
        /// </summary>
        internal static string String92 {
            get {
                return ResourceManager.GetString("String92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Desicion Tree is generated! 的本地化字符串。
        /// </summary>
        internal static string String93 {
            get {
                return ResourceManager.GetString("String93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicators 的本地化字符串。
        /// </summary>
        internal static string String94 {
            get {
                return ResourceManager.GetString("String94", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value 的本地化字符串。
        /// </summary>
        internal static string String95 {
            get {
                return ResourceManager.GetString("String95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Accuracy of decision tree 的本地化字符串。
        /// </summary>
        internal static string String96 {
            get {
                return ResourceManager.GetString("String96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kappa 的本地化字符串。
        /// </summary>
        internal static string String97 {
            get {
                return ResourceManager.GetString("String97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scale of training data set in all data 的本地化字符串。
        /// </summary>
        internal static string String98 {
            get {
                return ResourceManager.GetString("String98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Number of records in training data set 的本地化字符串。
        /// </summary>
        internal static string String99 {
            get {
                return ResourceManager.GetString("String99", resourceCulture);
            }
        }
    }
}
