//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoSOS.ArcMapAddIn.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_zh_CHS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_zh_CHS() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeoSOS.ArcMapAddIn.Properties.Resource_zh_CHS", typeof(Resource_zh_CHS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 人工神经网络元胞自动机模拟设置向导 的本地化字符串。
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 还未选择完成图层的土地利用类型 的本地化字符串。
        /// </summary>
        internal static string String10 {
            get {
                return ResourceManager.GetString("String10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进行基于逻辑回归的CA模拟设置如下： 的本地化字符串。
        /// </summary>
        internal static string String100 {
            get {
                return ResourceManager.GetString("String100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始时间为： 的本地化字符串。
        /// </summary>
        internal static string String101 {
            get {
                return ResourceManager.GetString("String101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人工神经网络CA模拟， 的本地化字符串。
        /// </summary>
        internal static string String102 {
            get {
                return ResourceManager.GetString("String102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 决策树CA模拟， 的本地化字符串。
        /// </summary>
        internal static string String103 {
            get {
                return ResourceManager.GetString("String103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 逻辑回归CA模拟， 的本地化字符串。
        /// </summary>
        internal static string String104 {
            get {
                return ResourceManager.GetString("String104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模拟精度 的本地化字符串。
        /// </summary>
        internal static string String105 {
            get {
                return ResourceManager.GetString("String105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    该向导将引导您进行基于人工神经网络方法的元胞自动机模拟。 的本地化字符串。
        /// </summary>
        internal static string String106 {
            get {
                return ResourceManager.GetString("String106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人工神经网络元胞自动机介绍 的本地化字符串。
        /// </summary>
        internal static string String107 {
            get {
                return ResourceManager.GetString("String107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   了解基于人工神经网络算法元胞自动机的基本原理。 的本地化字符串。
        /// </summary>
        internal static string String108 {
            get {
                return ResourceManager.GetString("String108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空间变量图层名称 的本地化字符串。
        /// </summary>
        internal static string String109 {
            get {
                return ResourceManager.GetString("String109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在抽样..... 的本地化字符串。
        /// </summary>
        internal static string String11 {
            get {
                return ResourceManager.GetString("String11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 土地利用类型值 的本地化字符串。
        /// </summary>
        internal static string String110 {
            get {
                return ResourceManager.GetString("String110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 土地利用类型说明 的本地化字符串。
        /// </summary>
        internal static string String111 {
            get {
                return ResourceManager.GetString("String111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否是城市用地 的本地化字符串。
        /// </summary>
        internal static string String112 {
            get {
                return ResourceManager.GetString("String112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用颜色 的本地化字符串。
        /// </summary>
        internal static string String113 {
            get {
                return ResourceManager.GetString("String113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 训练数据设置 的本地化字符串。
        /// </summary>
        internal static string String114 {
            get {
                return ResourceManager.GetString("String114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  设置训练人工神经网络将使用的空间数据。 的本地化字符串。
        /// </summary>
        internal static string String115 {
            get {
                return ResourceManager.GetString("String115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抽样数据 的本地化字符串。
        /// </summary>
        internal static string String116 {
            get {
                return ResourceManager.GetString("String116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  获取人工神经网络的抽样数据。 的本地化字符串。
        /// </summary>
        internal static string String117 {
            get {
                return ResourceManager.GetString("String117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人工神经网络训练 的本地化字符串。
        /// </summary>
        internal static string String118 {
            get {
                return ResourceManager.GetString("String118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  训练人工神经网络进行土地利用类型的预测。 的本地化字符串。
        /// </summary>
        internal static string String119 {
            get {
                return ResourceManager.GetString("String119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在读取初始时刻影像 的本地化字符串。
        /// </summary>
        internal static string String12 {
            get {
                return ResourceManager.GetString("String12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模拟数据设置 的本地化字符串。
        /// </summary>
        internal static string String120 {
            get {
                return ResourceManager.GetString("String120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  设置模拟要使用的数据。 的本地化字符串。
        /// </summary>
        internal static string String121 {
            get {
                return ResourceManager.GetString("String121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模拟参数设定 的本地化字符串。
        /// </summary>
        internal static string String122 {
            get {
                return ResourceManager.GetString("String122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  设置模拟所需的各类参数。 的本地化字符串。
        /// </summary>
        internal static string String123 {
            get {
                return ResourceManager.GetString("String123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模拟过程参数设置 的本地化字符串。
        /// </summary>
        internal static string String124 {
            get {
                return ResourceManager.GetString("String124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  设置模拟过程中的配置。 的本地化字符串。
        /// </summary>
        internal static string String125 {
            get {
                return ResourceManager.GetString("String125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模拟设置完成 的本地化字符串。
        /// </summary>
        internal static string String126 {
            get {
                return ResourceManager.GetString("String126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  检查以下摘要信息。单击“完成”以进行模拟。 的本地化字符串。
        /// </summary>
        internal static string String127 {
            get {
                return ResourceManager.GetString("String127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 土地利用类型性质 的本地化字符串。
        /// </summary>
        internal static string String128 {
            get {
                return ResourceManager.GetString("String128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 变量名称 的本地化字符串。
        /// </summary>
        internal static string String129 {
            get {
                return ResourceManager.GetString("String129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在读取终止时刻影像 的本地化字符串。
        /// </summary>
        internal static string String13 {
            get {
                return ResourceManager.GetString("String13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系数值 的本地化字符串。
        /// </summary>
        internal static string String130 {
            get {
                return ResourceManager.GetString("String130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准差 的本地化字符串。
        /// </summary>
        internal static string String131 {
            get {
                return ResourceManager.GetString("String131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 95%置信区间上限 的本地化字符串。
        /// </summary>
        internal static string String132 {
            get {
                return ResourceManager.GetString("String132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 95%置信区间下限 的本地化字符串。
        /// </summary>
        internal static string String133 {
            get {
                return ResourceManager.GetString("String133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 逻辑回归元胞自动机模拟设置向导 的本地化字符串。
        /// </summary>
        internal static string String134 {
            get {
                return ResourceManager.GetString("String134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  该向导将引导您进行基于逻辑回归方法的元胞自动机模拟。 的本地化字符串。
        /// </summary>
        internal static string String135 {
            get {
                return ResourceManager.GetString("String135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 逻辑回归元胞自动机介绍 的本地化字符串。
        /// </summary>
        internal static string String136 {
            get {
                return ResourceManager.GetString("String136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  了解基于逻辑回归算法元胞自动机的基本原理。 的本地化字符串。
        /// </summary>
        internal static string String137 {
            get {
                return ResourceManager.GetString("String137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  设置逻辑回归分析将使用的空间数据。 的本地化字符串。
        /// </summary>
        internal static string String138 {
            get {
                return ResourceManager.GetString("String138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置土地利用类型 的本地化字符串。
        /// </summary>
        internal static string String139 {
            get {
                return ResourceManager.GetString("String139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在读取变量影像 的本地化字符串。
        /// </summary>
        internal static string String14 {
            get {
                return ResourceManager.GetString("String14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  设置每一种土地利用类型的值、名称、性质和颜色。 的本地化字符串。
        /// </summary>
        internal static string String140 {
            get {
                return ResourceManager.GetString("String140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 逻辑回归分析 的本地化字符串。
        /// </summary>
        internal static string String141 {
            get {
                return ResourceManager.GetString("String141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  计算各变量的回归系数。 的本地化字符串。
        /// </summary>
        internal static string String142 {
            get {
                return ResourceManager.GetString("String142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 决策树元胞自动机模拟设置向导 的本地化字符串。
        /// </summary>
        internal static string String143 {
            get {
                return ResourceManager.GetString("String143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该向导将引导您进行基于决策树方法的元胞自动机模拟。 的本地化字符串。
        /// </summary>
        internal static string String144 {
            get {
                return ResourceManager.GetString("String144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 决策树元胞自动机介绍 的本地化字符串。
        /// </summary>
        internal static string String145 {
            get {
                return ResourceManager.GetString("String145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  了解基于决策树算法元胞自动机的基本原理。 的本地化字符串。
        /// </summary>
        internal static string String146 {
            get {
                return ResourceManager.GetString("String146", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  设置训练决策树将使用的空间数据。 的本地化字符串。
        /// </summary>
        internal static string String147 {
            get {
                return ResourceManager.GetString("String147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成决策树 的本地化字符串。
        /// </summary>
        internal static string String148 {
            get {
                return ResourceManager.GetString("String148", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  构建包含所有土地利用转换规则的决策树。 的本地化字符串。
        /// </summary>
        internal static string String149 {
            get {
                return ResourceManager.GetString("String149", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 截距 的本地化字符串。
        /// </summary>
        internal static string String15 {
            get {
                return ResourceManager.GetString("String15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 栅格数量总计 的本地化字符串。
        /// </summary>
        internal static string String150 {
            get {
                return ResourceManager.GetString("String150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 土地开发强度(%) 的本地化字符串。
        /// </summary>
        internal static string String151 {
            get {
                return ResourceManager.GetString("String151", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 城乡建设用地增长率(%) 的本地化字符串。
        /// </summary>
        internal static string String152 {
            get {
                return ResourceManager.GetString("String152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择土地利用分类数据进行统计。 的本地化字符串。
        /// </summary>
        internal static string String153 {
            get {
                return ResourceManager.GetString("String153", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存为Excel文件 的本地化字符串。
        /// </summary>
        internal static string String154 {
            get {
                return ResourceManager.GetString("String154", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Excel文件已保存。 的本地化字符串。
        /// </summary>
        internal static string String155 {
            get {
                return ResourceManager.GetString("String155", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 说明：进行同一区域两个时段土地利用分类数据对比，可得到混淆矩阵及Kappa值。 的本地化字符串。
        /// </summary>
        internal static string String156 {
            get {
                return ResourceManager.GetString("String156", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起始时期土地利用分类数据： 的本地化字符串。
        /// </summary>
        internal static string String157 {
            get {
                return ResourceManager.GetString("String157", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 终止时期土地利用分类数据： 的本地化字符串。
        /// </summary>
        internal static string String158 {
            get {
                return ResourceManager.GetString("String158", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模拟结果数据： 的本地化字符串。
        /// </summary>
        internal static string String159 {
            get {
                return ResourceManager.GetString("String159", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择需要模拟的开始时刻土地利用分类影像。 的本地化字符串。
        /// </summary>
        internal static string String16 {
            get {
                return ResourceManager.GetString("String16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 说明：进行模拟结果与真实土地利用分类数据对比，可得到混淆矩阵、Kappa值和各类精度值。 的本地化字符串。
        /// </summary>
        internal static string String160 {
            get {
                return ResourceManager.GetString("String160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模拟终止时刻真实土地利用分类数据： 的本地化字符串。
        /// </summary>
        internal static string String161 {
            get {
                return ResourceManager.GetString("String161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 说明：进行模拟起始时刻、终止时刻真实土地利用分类数据与模拟结果对比，可得到基于FoM的各类结果值。 的本地化字符串。
        /// </summary>
        internal static string String162 {
            get {
                return ResourceManager.GetString("String162", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已加载默认目标函数和蚁群算法参数，请点击工具条上的“开始”按钮执行优化过程。 的本地化字符串。
        /// </summary>
        internal static string String163 {
            get {
                return ResourceManager.GetString("String163", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行基于蚁群算法的面优化问题求解，请使用面优化面板进行设置。 的本地化字符串。
        /// </summary>
        internal static string String164 {
            get {
                return ResourceManager.GetString("String164", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未打开示例的Mxd文档。请打开AddIn安装目录中示例数据目录下的Optimization_DongGuang.mxd文件。 的本地化字符串。
        /// </summary>
        internal static string String165 {
            get {
                return ResourceManager.GetString("String165", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 面优化效用函数设置或蚁群算法参数设置未完成。请在设置窗体中完成设置。 的本地化字符串。
        /// </summary>
        internal static string String166 {
            get {
                return ResourceManager.GetString("String166", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基于蚁群算法的面优化， 的本地化字符串。
        /// </summary>
        internal static string String167 {
            get {
                return ResourceManager.GetString("String167", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 还未选择需要执行的模拟或优化方法，请点击工具条上的模拟或优化方法执行相应过程。 的本地化字符串。
        /// </summary>
        internal static string String168 {
            get {
                return ResourceManager.GetString("String168", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在创建生态适宜性数据 的本地化字符串。
        /// </summary>
        internal static string String169 {
            get {
                return ResourceManager.GetString("String169", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未打开示例的Mxd文档。请打开AddIn安装目录中示例数据目录下的LandUseChange_DongGuan.mxd文件。 的本地化字符串。
        /// </summary>
        internal static string String17 {
            get {
                return ResourceManager.GetString("String17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经完成面优化过程。效用函数的最大值为： 的本地化字符串。
        /// </summary>
        internal static string String170 {
            get {
                return ResourceManager.GetString("String170", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加限制图层 的本地化字符串。
        /// </summary>
        internal static string String171 {
            get {
                return ResourceManager.GetString("String171", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进行基于决策树的CA模拟设置如下： 的本地化字符串。
        /// </summary>
        internal static string String18 {
            get {
                return ResourceManager.GetString("String18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 涉及的空间变量的回归系数： 的本地化字符串。
        /// </summary>
        internal static string String19 {
            get {
                return ResourceManager.GetString("String19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常数 的本地化字符串。
        /// </summary>
        internal static string String20 {
            get {
                return ResourceManager.GetString("String20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  系数为： 的本地化字符串。
        /// </summary>
        internal static string String21 {
            get {
                return ResourceManager.GetString("String21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本次模拟的转换总量为： 的本地化字符串。
        /// </summary>
        internal static string String22 {
            get {
                return ResourceManager.GetString("String22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  个栅格单元。 的本地化字符串。
        /// </summary>
        internal static string String23 {
            get {
                return ResourceManager.GetString("String23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  次。 的本地化字符串。
        /// </summary>
        internal static string String24 {
            get {
                return ResourceManager.GetString("String24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每次迭代的转换量为： 的本地化字符串。
        /// </summary>
        internal static string String25 {
            get {
                return ResourceManager.GetString("String25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扩散系数： 的本地化字符串。
        /// </summary>
        internal static string String26 {
            get {
                return ResourceManager.GetString("String26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 城市用地类型的对应值为： 的本地化字符串。
        /// </summary>
        internal static string String27 {
            get {
                return ResourceManager.GetString("String27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  数值为： 的本地化字符串。
        /// </summary>
        internal static string String28 {
            get {
                return ResourceManager.GetString("String28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可以转换为城市用地类型的对应值为： 的本地化字符串。
        /// </summary>
        internal static string String29 {
            get {
                return ResourceManager.GetString("String29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 还未选择提取规则时要使用的初始土地利用分类影像。请选择初始土地利用分类影像。 的本地化字符串。
        /// </summary>
        internal static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不可以转换为城市用地类型的对应值为： 的本地化字符串。
        /// </summary>
        internal static string String30 {
            get {
                return ResourceManager.GetString("String30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模拟要迭代的次数为： 的本地化字符串。
        /// </summary>
        internal static string String31 {
            get {
                return ResourceManager.GetString("String31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模拟过程控制： 的本地化字符串。
        /// </summary>
        internal static string String32 {
            get {
                return ResourceManager.GetString("String32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每  的本地化字符串。
        /// </summary>
        internal static string String33 {
            get {
                return ResourceManager.GetString("String33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  次迭代刷新一次输出结果和图表。 的本地化字符串。
        /// </summary>
        internal static string String34 {
            get {
                return ResourceManager.GetString("String34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  次迭代输出一次中间结果图像。 的本地化字符串。
        /// </summary>
        internal static string String35 {
            get {
                return ResourceManager.GetString("String35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出位置： 的本地化字符串。
        /// </summary>
        internal static string String36 {
            get {
                return ResourceManager.GetString("String36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在创建模拟结果影像 的本地化字符串。
        /// </summary>
        internal static string String37 {
            get {
                return ResourceManager.GetString("String37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已完成CA模拟设置。点击GeoSOS工具栏中的开始按钮可以开始模拟过程。 的本地化字符串。
        /// </summary>
        internal static string String38 {
            get {
                return ResourceManager.GetString("String38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前正在运行模拟，请先停止当前模拟再重新进行模拟。 的本地化字符串。
        /// </summary>
        internal static string String39 {
            get {
                return ResourceManager.GetString("String39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 还未选择提取规则时要使用的终止土地利用分类影像。请选择终止土地利用分类影像。 的本地化字符串。
        /// </summary>
        internal static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 土地利用类型用地量变化 的本地化字符串。
        /// </summary>
        internal static string String40 {
            get {
                return ResourceManager.GetString("String40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 迭代次数 的本地化字符串。
        /// </summary>
        internal static string String41 {
            get {
                return ResourceManager.GetString("String41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用地量 的本地化字符串。
        /// </summary>
        internal static string String42 {
            get {
                return ResourceManager.GetString("String42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始模拟过程: 的本地化字符串。
        /// </summary>
        internal static string String43 {
            get {
                return ResourceManager.GetString("String43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据空值 的本地化字符串。
        /// </summary>
        internal static string String44 {
            get {
                return ResourceManager.GetString("String44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前迭代次数：第  的本地化字符串。
        /// </summary>
        internal static string String45 {
            get {
                return ResourceManager.GetString("String45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  次 的本地化字符串。
        /// </summary>
        internal static string String46 {
            get {
                return ResourceManager.GetString("String46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前城市单元的数量： 的本地化字符串。
        /// </summary>
        internal static string String47 {
            get {
                return ResourceManager.GetString("String47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成模拟过程。 的本地化字符串。
        /// </summary>
        internal static string String48 {
            get {
                return ResourceManager.GetString("String48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本次模拟用时： 的本地化字符串。
        /// </summary>
        internal static string String49 {
            get {
                return ResourceManager.GetString("String49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 还未选择模拟的空间变量影像。请选择空间变量影像。 的本地化字符串。
        /// </summary>
        internal static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  秒。 的本地化字符串。
        /// </summary>
        internal static string String50 {
            get {
                return ResourceManager.GetString("String50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转换结果 的本地化字符串。
        /// </summary>
        internal static string String51 {
            get {
                return ResourceManager.GetString("String51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XML文件(*.xml)|*.xml 的本地化字符串。
        /// </summary>
        internal static string String52 {
            get {
                return ResourceManager.GetString("String52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开土地利用类型信息配置文件 的本地化字符串。
        /// </summary>
        internal static string String53 {
            get {
                return ResourceManager.GetString("String53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存土地利用类型信息配置文件 的本地化字符串。
        /// </summary>
        internal static string String54 {
            get {
                return ResourceManager.GetString("String54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已保存配置文件。 的本地化字符串。
        /// </summary>
        internal static string String55 {
            get {
                return ResourceManager.GetString("String55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CA模拟-逻辑回归方法 的本地化字符串。
        /// </summary>
        internal static string String56 {
            get {
                return ResourceManager.GetString("String56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能正在实现中。 的本地化字符串。
        /// </summary>
        internal static string String57 {
            get {
                return ResourceManager.GetString("String57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取数据： 的本地化字符串。
        /// </summary>
        internal static string String58 {
            get {
                return ResourceManager.GetString("String58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前过程已暂停 的本地化字符串。
        /// </summary>
        internal static string String59 {
            get {
                return ResourceManager.GetString("String59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可转换为城市用地 的本地化字符串。
        /// </summary>
        internal static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前过程已继续执行 的本地化字符串。
        /// </summary>
        internal static string String60 {
            get {
                return ResourceManager.GetString("String60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前过程已停止 的本地化字符串。
        /// </summary>
        internal static string String61 {
            get {
                return ResourceManager.GetString("String61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请打开AddIn安装目录下Help目录中的GeoSOS for ArcGIS User Manual_CHS.pdf文件。或访问http://www.geosimulation.cn/usermanual_arcgisaddin.html获取帮助。 的本地化字符串。
        /// </summary>
        internal static string String62 {
            get {
                return ResourceManager.GetString("String62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在生成决策树，需要一定时间，请耐心等待..... 的本地化字符串。
        /// </summary>
        internal static string String63 {
            get {
                return ResourceManager.GetString("String63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抽样数据共有  的本地化字符串。
        /// </summary>
        internal static string String64 {
            get {
                return ResourceManager.GetString("String64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  条。  的本地化字符串。
        /// </summary>
        internal static string String65 {
            get {
                return ResourceManager.GetString("String65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请勾选某种土地利用类型为城市用地类型 的本地化字符串。
        /// </summary>
        internal static string String66 {
            get {
                return ResourceManager.GetString("String66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 还未完成人工神经网络训练。请点击“开始训练”按钮进行训练。 的本地化字符串。
        /// </summary>
        internal static string String67 {
            get {
                return ResourceManager.GetString("String67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已完成抽样! 的本地化字符串。
        /// </summary>
        internal static string String68 {
            get {
                return ResourceManager.GetString("String68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人工神经网络已完成训练 的本地化字符串。
        /// </summary>
        internal static string String69 {
            get {
                return ResourceManager.GetString("String69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不可转换为城市用地 的本地化字符串。
        /// </summary>
        internal static string String7 {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开转换适宜性设置文件 的本地化字符串。
        /// </summary>
        internal static string String70 {
            get {
                return ResourceManager.GetString("String70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存转换适宜性设置文件 的本地化字符串。
        /// </summary>
        internal static string String71 {
            get {
                return ResourceManager.GetString("String71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进行基于人工神经网络的CA模拟设置如下： 的本地化字符串。
        /// </summary>
        internal static string String72 {
            get {
                return ResourceManager.GetString("String72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空间影响因子图层为： 的本地化字符串。
        /// </summary>
        internal static string String73 {
            get {
                return ResourceManager.GetString("String73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 土地利用类型包括： 的本地化字符串。
        /// </summary>
        internal static string String74 {
            get {
                return ResourceManager.GetString("String74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邻域窗口大小为： 的本地化字符串。
        /// </summary>
        internal static string String75 {
            get {
                return ResourceManager.GetString("String75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模拟起始的土地利用数据： 的本地化字符串。
        /// </summary>
        internal static string String76 {
            get {
                return ResourceManager.GetString("String76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模拟终止进行对比的土地利用数据： 的本地化字符串。
        /// </summary>
        internal static string String77 {
            get {
                return ResourceManager.GetString("String77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转换阈值为： 的本地化字符串。
        /// </summary>
        internal static string String78 {
            get {
                return ResourceManager.GetString("String78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 土地利用类型相互转变的适宜性为： 的本地化字符串。
        /// </summary>
        internal static string String79 {
            get {
                return ResourceManager.GetString("String79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 城市用地 的本地化字符串。
        /// </summary>
        internal static string String8 {
            get {
                return ResourceManager.GetString("String8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CA模拟-人工神经网络方法 的本地化字符串。
        /// </summary>
        internal static string String80 {
            get {
                return ResourceManager.GetString("String80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CA模拟-决策树方法 的本地化字符串。
        /// </summary>
        internal static string String81 {
            get {
                return ResourceManager.GetString("String81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始 的本地化字符串。
        /// </summary>
        internal static string String82 {
            get {
                return ResourceManager.GetString("String82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本次模拟的精度： 的本地化字符串。
        /// </summary>
        internal static string String83 {
            get {
                return ResourceManager.GetString("String83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模拟结果的混淆矩阵为： 的本地化字符串。
        /// </summary>
        internal static string String84 {
            get {
                return ResourceManager.GetString("String84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模拟的总精度： 的本地化字符串。
        /// </summary>
        internal static string String85 {
            get {
                return ResourceManager.GetString("String85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kappa系数： 的本地化字符串。
        /// </summary>
        internal static string String86 {
            get {
                return ResourceManager.GetString("String86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FoM精度值： 的本地化字符串。
        /// </summary>
        internal static string String87 {
            get {
                return ResourceManager.GetString("String87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产者精度值： 的本地化字符串。
        /// </summary>
        internal static string String88 {
            get {
                return ResourceManager.GetString("String88", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户精度值： 的本地化字符串。
        /// </summary>
        internal static string String89 {
            get {
                return ResourceManager.GetString("String89", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在计算..... 的本地化字符串。
        /// </summary>
        internal static string String9 {
            get {
                return ResourceManager.GetString("String9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 整体 的本地化字符串。
        /// </summary>
        internal static string String90 {
            get {
                return ResourceManager.GetString("String90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 栅格数量 的本地化字符串。
        /// </summary>
        internal static string String91 {
            get {
                return ResourceManager.GetString("String91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 百分比 的本地化字符串。
        /// </summary>
        internal static string String92 {
            get {
                return ResourceManager.GetString("String92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 决策树生成完成! 的本地化字符串。
        /// </summary>
        internal static string String93 {
            get {
                return ResourceManager.GetString("String93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指标名称 的本地化字符串。
        /// </summary>
        internal static string String94 {
            get {
                return ResourceManager.GetString("String94", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指标值 的本地化字符串。
        /// </summary>
        internal static string String95 {
            get {
                return ResourceManager.GetString("String95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 决策树精度 的本地化字符串。
        /// </summary>
        internal static string String96 {
            get {
                return ResourceManager.GetString("String96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kappa系数 的本地化字符串。
        /// </summary>
        internal static string String97 {
            get {
                return ResourceManager.GetString("String97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 训练集记录比例 的本地化字符串。
        /// </summary>
        internal static string String98 {
            get {
                return ResourceManager.GetString("String98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 训练集记录数 的本地化字符串。
        /// </summary>
        internal static string String99 {
            get {
                return ResourceManager.GetString("String99", resourceCulture);
            }
        }
    }
}
